// بيانات المحادثات
export const mockConversations = [
  {
    id: "c-1",
    customerName: "يحيى الحسني",
    customerInitials: "يح",
    phone: "0661XXXXXX",
    lastMessage: "غالي شوية، واش كاين تخفيض؟",
    stage: "OBJECTION",
    score: 70,
    messagesCount: 8,
    isRead: false,
    totalAmount: null,
    createdAt: "2026-03-17T10:35:00",
    updatedAt: "2026-03-17T10:35:00",
  },
  {
    id: "c-2",
    customerName: "سناء بنعلي",
    customerInitials: "سن",
    phone: "0662XXXXXX",
    lastMessage: "شكراً، وصل الطلب بخير 🌸",
    stage: "CLOSED",
    score: 100,
    messagesCount: 12,
    isRead: true,
    totalAmount: 320,
    createdAt: "2026-03-17T10:20:00",
    updatedAt: "2026-03-17T10:38:00",
  },
  {
    id: "c-3",
    customerName: "كريم الزياني",
    customerInitials: "كز",
    phone: "0663XXXXXX",
    lastMessage: "مش محتاجه دابا...",
    stage: "OBJECTION",
    score: 30,
    messagesCount: 5,
    isRead: false,
    totalAmount: null,
    createdAt: "2026-03-17T09:55:00",
    updatedAt: "2026-03-17T09:55:00",
  },
  {
    id: "c-4",
    customerName: "أمينة العلوي",
    customerInitials: "أع",
    phone: "0664XXXXXX",
    lastMessage: "عجبني القماش، شكراً بزاف!",
    stage: "CLOSED",
    score: 100,
    messagesCount: 15,
    isRead: true,
    totalAmount: 580,
    createdAt: "2026-03-17T09:20:00",
    updatedAt: "2026-03-17T09:20:00",
  },
  {
    id: "c-5",
    customerName: "مريم بنسعيد",
    customerInitials: "مب",
    phone: "0664XXXXXX",
    lastMessage: "واش كاين مقاس XL؟",
    stage: "PITCHING",
    score: 55,
    messagesCount: 4,
    isRead: false,
    totalAmount: null,
    createdAt: "2026-03-17T11:02:00",
    updatedAt: "2026-03-17T11:02:00",
  },
]

// بيانات المنتجات
export const mockProducts = [
  { id: "p-1", name: "جلباب زيتوني", price: 320, questions: 47, isActive: true, description: "قماش درابزين أصلي، ألوان متعددة" },
  { id: "p-2", name: "كافطان صيفي", price: 480, questions: 31, isActive: true, description: "خامة خفيفة مناسبة للصيف" },
  { id: "p-3", name: "حجاب شيفون", price: 85, questions: 22, isActive: true, description: "ناعم وخفيف، ألوان كثيرة" },
  { id: "p-4", name: "فستان سهرة", price: 650, questions: 18, isActive: true, description: "مناسب للمناسبات الرسمية" },
  { id: "p-5", name: "عباية كلاسيكية", price: 420, questions: 15, isActive: false, description: "تصميم كلاسيكي أنيق" },
]

// بيانات الزبائن
export const mockCustomers = [
  { id: "cu-1", name: "سناء بنعلي", initials: "سن", phone: "0661XXXXXX", orders: 5, totalSpent: 1840, tag: "VIP", lastSeen: "اليوم" },
  { id: "cu-2", name: "أمينة العلوي", initials: "أع", phone: "0662XXXXXX", orders: 3, totalSpent: 1200, tag: "VIP", lastSeen: "أمس" },
  { id: "cu-3", name: "يحيى الحسني", initials: "يح", phone: "0663XXXXXX", orders: 1, totalSpent: 320, tag: "NEW", lastSeen: "اليوم" },
  { id: "cu-4", name: "مريم بنسعيد", initials: "مب", phone: "0664XXXXXX", orders: 2, totalSpent: 760, tag: "REGULAR", lastSeen: "منذ 3 أيام" },
  { id: "cu-5", name: "كريم الزياني", initials: "كز", phone: "0665XXXXXX", orders: 0, totalSpent: 0, tag: "PROSPECT", lastSeen: "اليوم" },
]

// بيانات الإحصائيات
export const mockStats = {
  todayConversations: 47,
  todaySales: 8,
  conversionRate: 17,
  todayRevenue: 3240,
  pitching: 14,
  weekConversations: 312,
  weekRevenue: 18640,
  avgOrderValue: 386,
  avgResponseTime: "2.3 ث",
  satisfactionRate: 92,
  returnRate: 34,
  stages: {
    greeting: 47,
    discovery: 35,
    pitching: 22,
    objection: 12,
    closed: 8,
  },
  weeklyChart: [45, 62, 38, 75, 55, 90, 47],
  weeklyDays: ["إث", "ثل", "أر", "خم", "جم", "سب", "أح"],
  objectionReasons: [
    { reason: "السعر غالي", count: 65 },
    { reason: "نفكر فيها", count: 42 },
    { reason: "مش المقاس", count: 28 },
    { reason: "اللون مش كاين", count: 18 },
  ],
}
