-- SQL مطابق لـ Prisma Schema
-- Table names: users, agents, products, conversations, messages, customers, notifications

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password VARCHAR(191) NOT NULL,
  phone VARCHAR(191),
  storeName VARCHAR(191) NOT NULL,
  plan ENUM('FREE', 'PRO', 'ENTERPRISE') DEFAULT 'FREE',
  isActive BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL UNIQUE,
  name VARCHAR(191) NOT NULL DEFAULT 'Agent',
  domain VARCHAR(191) NOT NULL DEFAULT 'تجارة عامة',
  style VARCHAR(191) NOT NULL DEFAULT 'friendly',
  language VARCHAR(191) NOT NULL DEFAULT 'darija',
  isActive BOOLEAN NOT NULL DEFAULT true,
  instructions TEXT,
  whatsappPhoneId VARCHAR(191),
  whatsappToken TEXT,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS objection_replies (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  agentId VARCHAR(191) NOT NULL,
  `trigger` VARCHAR(191) NOT NULL,
  reply TEXT NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  FOREIGN KEY (agentId) REFERENCES agents(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  isActive BOOLEAN NOT NULL DEFAULT true,
  questions INT NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS customers (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  phone VARCHAR(191) NOT NULL,
  tag ENUM('NEW', 'REGULAR', 'VIP', 'PROSPECT') DEFAULT 'NEW',
  totalSpent DECIMAL(10,2) NOT NULL DEFAULT 0,
  ordersCount INT NOT NULL DEFAULT 0,
  lastSeen DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY unique_user_phone (userId, phone)
);

CREATE TABLE IF NOT EXISTS conversations (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  customerId VARCHAR(191) NOT NULL,
  stage ENUM('GREETING', 'DISCOVERY', 'PITCHING', 'OBJECTION', 'CLOSING', 'CLOSED', 'ABANDONED') DEFAULT 'GREETING',
  score INT NOT NULL DEFAULT 0,
  isRead BOOLEAN NOT NULL DEFAULT false,
  totalAmount DECIMAL(10,2),
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (customerId) REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  conversationId VARCHAR(191) NOT NULL,
  role ENUM('USER', 'AGENT') NOT NULL,
  content TEXT NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (conversationId) REFERENCES conversations(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  type ENUM('NEW_ORDER', 'OBJECTION_ALERT', 'DAILY_REPORT', 'AGENT_DOWN', 'SYSTEM') DEFAULT 'SYSTEM',
  title VARCHAR(191) NOT NULL,
  message TEXT NOT NULL,
  isRead BOOLEAN NOT NULL DEFAULT false,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
