-- Run this in Aiven Console SQL Editor

CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  email VARCHAR(191) NOT NULL UNIQUE,
  name VARCHAR(191) NOT NULL,
  password VARCHAR(191) NOT NULL,
  phone VARCHAR(191),
  storeName VARCHAR(191) NOT NULL,
  plan VARCHAR(191) DEFAULT 'free',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS Agent (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  domain VARCHAR(191) NOT NULL,
  style VARCHAR(191) NOT NULL,
  language VARCHAR(191) NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT true,
  instructions TEXT,
  whatsappPhoneId VARCHAR(191),
  whatsappToken TEXT,
  userId VARCHAR(191) NOT NULL UNIQUE,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ObjectionReply (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  trigger VARCHAR(191) NOT NULL,
  reply TEXT NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  agentId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (agentId) REFERENCES Agent(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Product (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  image VARCHAR(191),
  category VARCHAR(191),
  isActive BOOLEAN NOT NULL DEFAULT true,
  userId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Customer (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  phone VARCHAR(191) NOT NULL,
  email VARCHAR(191),
  whatsappId VARCHAR(191),
  tags VARCHAR(191),
  notes TEXT,
  lastOrderAt DATETIME(3),
  totalOrders INT NOT NULL DEFAULT 0,
  totalSpent DECIMAL(10,2) NOT NULL DEFAULT 0,
  userId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Conversation (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  customerId VARCHAR(191) NOT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'active',
  source VARCHAR(191) NOT NULL DEFAULT 'whatsapp',
  lastMessageAt DATETIME(3),
  userId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  FOREIGN KEY (customerId) REFERENCES Customer(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Message (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  content TEXT NOT NULL,
  sender VARCHAR(191) NOT NULL,
  type VARCHAR(191) NOT NULL DEFAULT 'text',
  status VARCHAR(191) NOT NULL DEFAULT 'sent',
  conversationId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Notification (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  title VARCHAR(191) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(191) NOT NULL DEFAULT 'info',
  isRead BOOLEAN NOT NULL DEFAULT false,
  userId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);
